# Site settings
title: Derek Croote
motto: Science, engineering, and data. Sometimes with humor.
author:
  name: Derek Croote
  twitter: DerekCroote
email: dcroote@gmail.com
baseurl: ""
url: "https://www.derekcroote.com"
github_username: dcroote
twitter_username: DerekCroote
twitter:
  username: DerekCroote
  card: summary_large_image
description: Perspectives on science, technology, and engineering.

# Build settings
markdown: kramdown

include: [".well-known", "manifest.json", "sw.js"]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
